fix bugsnag messages when logs are empty
coinbase/salus pull request #326
Opened 2021-03-18 10:21 UTC by Kamsiy

2021-03-18 14:51 UTC, joshua-ostrom commented on lib/sarif/bandit_sarif.rb
> +      logs = @scan_report.log('')
return [] if logs.size.zero?

2021-03-18 14:52 UTC, joshua-ostrom commented on lib/sarif/brakeman_sarif.rb
> +      logs = @scan_report.log('')
return [] if logs.size.zero?

2021-03-18 14:52 UTC, joshua-ostrom commented on lib/sarif/cargo_audit_sarif.rb
> +      if !logs.size.zero?
return [] if logs.size.zero?

2021-03-18 14:52 UTC, joshua-ostrom commented on lib/sarif/gosec_sarif.rb
> +      log = scan_report.log("")
return [] if logs.size.zero?

2021-03-18 16:16 UTC, joshua-ostrom requested changes
Changes looks good.  Can we add a spec coverage on this?  (Happy to pair if needed).  I would not let that hold up a patch though.

2021-03-26 10:25 UTC, ghbren approved these changes

2021-03-26 10:28 UTC, ghbren approved these changes

2021-03-26 16:10 UTC, joshua-ostrom approved these changes

2021-03-26 16:10 UTC, merged